<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="57" passed="57" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-01-13T00:38:51 EST" name="Default Suite" finished-at="2022-01-13T00:39:00 EST" duration-ms="8974">
    <groups>
    </groups>
    <test started-at="2022-01-13T00:38:51 EST" name="JAVA_investing_app" finished-at="2022-01-13T00:39:00 EST" duration-ms="8974">
      <class name="dev.commentingservicetests.CommentingServiceTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="setup" finished-at="2022-01-13T00:39:00 EST" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="badCommentDateMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="badCommentDateMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.TooLong">
            <message>
              <![CDATA[Your input is too many characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooLong: Your input is too many characters
at com.investing_app.service.CommentingServicesImp.createCommentService(CommentingServicesImp.java:20)
at dev.commentingservicetests.CommentingServiceTests.badCommentDateMockito(CommentingServiceTests.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooLong -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badCommentDateMockito -->
        <test-method signature="badIdForCommentMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="badIdForCommentMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.CommentNotFound">
            <message>
              <![CDATA[Comment not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.CommentNotFound: Comment not found
at com.investing_app.service.CommentingServicesImp.getCommentByIdService(CommentingServicesImp.java:44)
at dev.commentingservicetests.CommentingServiceTests.badIdForCommentMockito(CommentingServiceTests.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.CommentNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- badIdForCommentMockito -->
        <test-method signature="createCommentMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="createCommentMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCommentMockito -->
        <test-method signature="getAllComments()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="getAllComments" finished-at="2022-01-13T00:39:00 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllComments -->
        <test-method signature="getCommentMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="getCommentMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCommentMockito -->
        <test-method signature="noCommentMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="noCommentMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.NoValueException">
            <message>
              <![CDATA[Cannot leave boxes empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NoValueException: Cannot leave boxes empty
at com.investing_app.service.CommentingServicesImp.createCommentService(CommentingServicesImp.java:24)
at dev.commentingservicetests.CommentingServiceTests.noCommentMockito(CommentingServiceTests.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NoValueException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noCommentMockito -->
        <test-method signature="noDateMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="noDateMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.NotValidDate">
            <message>
              <![CDATA[Must be 10 digits long]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NotValidDate: Must be 10 digits long
at com.investing_app.service.CommentingServicesImp.createCommentService(CommentingServicesImp.java:22)
at dev.commentingservicetests.CommentingServiceTests.noDateMockito(CommentingServiceTests.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NotValidDate -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- noDateMockito -->
        <test-method signature="tooLongCommentMockito()[pri:0, instance:dev.commentingservicetests.CommentingServiceTests@3ee0fea4]" started-at="2022-01-13T00:39:00 EST" name="tooLongCommentMockito" finished-at="2022-01-13T00:39:00 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.TooLong">
            <message>
              <![CDATA[Your input is too many characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooLong: Your input is too many characters
at com.investing_app.service.CommentingServicesImp.createCommentService(CommentingServicesImp.java:26)
at dev.commentingservicetests.CommentingServiceTests.tooLongCommentMockito(CommentingServiceTests.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooLong -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tooLongCommentMockito -->
      </class> <!-- dev.commentingservicetests.CommentingServiceTests -->
      <class name="dev.SharkTests.SharkDAOTests">
        <test-method signature="getAllSharks()[pri:0, instance:dev.SharkTests.SharkDAOTests@145eaa29]" started-at="2022-01-13T00:38:52 EST" name="getAllSharks" finished-at="2022-01-13T00:38:52 EST" duration-ms="926" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllSharks -->
        <test-method signature="getSharkByUsername()[pri:0, instance:dev.SharkTests.SharkDAOTests@145eaa29]" started-at="2022-01-13T00:38:52 EST" name="getSharkByUsername" finished-at="2022-01-13T00:38:53 EST" duration-ms="505" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getSharkByUsername -->
        <test-method signature="sharkCreateProfile()[pri:0, instance:dev.SharkTests.SharkDAOTests@145eaa29]" started-at="2022-01-13T00:38:53 EST" name="sharkCreateProfile" finished-at="2022-01-13T00:38:54 EST" duration-ms="574" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkCreateProfile -->
      </class> <!-- dev.SharkTests.SharkDAOTests -->
      <class name="dev.pitchtests.PitchServiceTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="setup" finished-at="2022-01-13T00:38:58 EST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="acceptOfferReturnedValue()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="acceptOfferReturnedValue" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acceptOfferReturnedValue -->
        <test-method signature="createPitchAmountTooHigh()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchAmountTooHigh" finished-at="2022-01-13T00:38:58 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.ValueTooLarge">
            <message>
              <![CDATA[Please enter an amount below one million dollars.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.ValueTooLarge: Please enter an amount below one million dollars.
at com.investing_app.service.PitchServiceImplemented.createPitchService(PitchServiceImplemented.java:25)
at dev.pitchtests.PitchServiceTests.createPitchAmountTooHigh(PitchServiceTests.java:120)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.ValueTooLarge -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchAmountTooHigh -->
        <test-method signature="createPitchIncorrectDataType()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchIncorrectDataType" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.IncorrectDataType">
            <message>
              <![CDATA[Input type not allowed!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.IncorrectDataType: Input type not allowed!
at com.investing_app.service.PitchServiceImplemented.createPitchService(PitchServiceImplemented.java:25)
at dev.pitchtests.PitchServiceTests.createPitchIncorrectDataType(PitchServiceTests.java:112)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.IncorrectDataType -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchIncorrectDataType -->
        <test-method signature="createPitchNullValue()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchNullValue" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.NullValue">
            <message>
              <![CDATA[You must enter a value!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NullValue: You must enter a value!
at com.investing_app.service.PitchServiceImplemented.createPitchService(PitchServiceImplemented.java:25)
at dev.pitchtests.PitchServiceTests.createPitchNullValue(PitchServiceTests.java:104)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NullValue -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchNullValue -->
        <test-method signature="createPitchPercentTooHigh()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchPercentTooHigh" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.ValueTooLarge">
            <message>
              <![CDATA[Please enter a percentage less than or equal to 100.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.ValueTooLarge: Please enter a percentage less than or equal to 100.
at com.investing_app.service.PitchServiceImplemented.createPitchService(PitchServiceImplemented.java:25)
at dev.pitchtests.PitchServiceTests.createPitchPercentTooHigh(PitchServiceTests.java:128)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.ValueTooLarge -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchPercentTooHigh -->
        <test-method signature="createPitchReturnedValue()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchReturnedValue" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchReturnedValue -->
        <test-method signature="createPitchTooManyChar()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="createPitchTooManyChar" finished-at="2022-01-13T00:38:58 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.TooManyChar">
            <message>
              <![CDATA[You are exceeding the value length!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooManyChar: You are exceeding the value length!
at com.investing_app.service.PitchServiceImplemented.createPitchService(PitchServiceImplemented.java:25)
at dev.pitchtests.PitchServiceTests.createPitchTooManyChar(PitchServiceTests.java:97)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooManyChar -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitchTooManyChar -->
        <test-method signature="makeOfferReturnedValue()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="makeOfferReturnedValue" finished-at="2022-01-13T00:38:58 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeOfferReturnedValue -->
        <test-method signature="viewPitchesReturnedValue()[pri:0, instance:dev.pitchtests.PitchServiceTests@2d9d4f9d]" started-at="2022-01-13T00:38:58 EST" name="viewPitchesReturnedValue" finished-at="2022-01-13T00:38:58 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewPitchesReturnedValue -->
      </class> <!-- dev.pitchtests.PitchServiceTests -->
      <class name="dev.SharkTests.SharkServiceTests">
        <test-method is-config="true" signature="setup()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="setup" finished-at="2022-01-13T00:38:54 EST" duration-ms="234" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createSharkProfileIncorrectDataType()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileIncorrectDataType" finished-at="2022-01-13T00:38:54 EST" duration-ms="4" status="PASS">
          <exception class="com.investing_app.customexceptions.IncorrectDataType">
            <message>
              <![CDATA[Input type not allowed]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.IncorrectDataType: Input type not allowed
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:36)
at dev.SharkTests.SharkServiceTests.createSharkProfileIncorrectDataType(SharkServiceTests.java:122)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.IncorrectDataType -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileIncorrectDataType -->
        <test-method signature="createSharkProfileNullValue()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileNullValue" finished-at="2022-01-13T00:38:54 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.NullValue">
            <message>
              <![CDATA[You must enter a value!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NullValue: You must enter a value!
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:25)
at dev.SharkTests.SharkServiceTests.createSharkProfileNullValue(SharkServiceTests.java:114)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NullValue -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileNullValue -->
        <test-method signature="createSharkProfileReturnedValue()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileReturnedValue" finished-at="2022-01-13T00:38:54 EST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileReturnedValue -->
        <test-method signature="createSharkProfileShortPassword()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileShortPassword" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.PasswordTooShort">
            <message>
              <![CDATA[Password must be at least 8 characters!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.PasswordTooShort: Password must be at least 8 characters!
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:32)
at dev.SharkTests.SharkServiceTests.createSharkProfileShortPassword(SharkServiceTests.java:146)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.PasswordTooShort -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileShortPassword -->
        <test-method signature="createSharkProfileShortUsername()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileShortUsername" finished-at="2022-01-13T00:38:54 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameTooShort">
            <message>
              <![CDATA[Username must be at least 5 characters!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameTooShort: Username must be at least 5 characters!
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:30)
at dev.SharkTests.SharkServiceTests.createSharkProfileShortUsername(SharkServiceTests.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameTooShort -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileShortUsername -->
        <test-method signature="createSharkProfileUniqueUsername()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileUniqueUsername" finished-at="2022-01-13T00:38:54 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameTaken">
            <message>
              <![CDATA[That username is already taken! Please try again.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameTaken: That username is already taken! Please try again.
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:41)
at dev.SharkTests.SharkServiceTests.createSharkProfileUniqueUsername(SharkServiceTests.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameTaken -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileUniqueUsername -->
        <test-method signature="createSharkProfileTooManyChar()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="createSharkProfileTooManyChar" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.TooManyChar">
            <message>
              <![CDATA[You are exceeding the value length]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooManyChar: You are exceeding the value length
at com.investing_app.service.SharkServiceImplemented.createSharkProfileService(SharkServiceImplemented.java:28)
at dev.SharkTests.SharkServiceTests.createSharkProfileTooManyChar(SharkServiceTests.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooManyChar -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSharkProfileTooManyChar -->
        <test-method signature="sharkLoginNullValues()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginNullValues" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.NullValue">
            <message>
              <![CDATA[You must enter a value!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NullValue: You must enter a value!
at com.investing_app.service.SharkServiceImplemented.sharkLoginService(SharkServiceImplemented.java:51)
at dev.SharkTests.SharkServiceTests.sharkLoginNullValues(SharkServiceTests.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NullValue -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginNullValues -->
        <test-method signature="sharkLoginPasswordFail()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginPasswordFail" finished-at="2022-01-13T00:38:54 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordIncorrect">
            <message>
              <![CDATA[Either your username or password or both are incorrect!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordIncorrect: Either your username or password or both are incorrect!
at dev.SharkTests.SharkServiceTests.sharkLoginUsernameFail(SharkServiceTests.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordIncorrect -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginPasswordFail -->
        <test-method signature="sharkLoginSuccess()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginSuccess" finished-at="2022-01-13T00:38:54 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginSuccess -->
        <test-method signature="sharkLoginServiceUsernamePasswordFail()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginServiceUsernamePasswordFail" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordIncorrect">
            <message>
              <![CDATA[Either your username or password or both are incorrect!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordIncorrect: Either your username or password or both are incorrect!
at com.investing_app.service.SharkServiceImplemented.sharkLoginService(SharkServiceImplemented.java:47)
at dev.SharkTests.SharkServiceTests.sharkLoginServiceUsernamePasswordFail(SharkServiceTests.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordIncorrect -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginServiceUsernamePasswordFail -->
        <test-method signature="sharkLoginTooManyChar()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginTooManyChar" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.TooManyChar">
            <message>
              <![CDATA[You are exceeding the value length]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooManyChar: You are exceeding the value length
at com.investing_app.service.SharkServiceImplemented.sharkLoginService(SharkServiceImplemented.java:49)
at dev.SharkTests.SharkServiceTests.sharkLoginTooManyChar(SharkServiceTests.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooManyChar -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginTooManyChar -->
        <test-method signature="sharkLoginUsernameFail()[pri:0, instance:dev.SharkTests.SharkServiceTests@17c386de]" started-at="2022-01-13T00:38:54 EST" name="sharkLoginUsernameFail" finished-at="2022-01-13T00:38:54 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordIncorrect">
            <message>
              <![CDATA[Either your username or password or both are incorrect!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordIncorrect: Either your username or password or both are incorrect!
at dev.SharkTests.SharkServiceTests.sharkLoginUsernameFail(SharkServiceTests.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordIncorrect -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sharkLoginUsernameFail -->
      </class> <!-- dev.SharkTests.SharkServiceTests -->
      <class name="dev.businessservicestests.BusinessServicesTests">
        <test-method is-config="true" signature="businessSetup()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="businessSetup" finished-at="2022-01-13T00:38:56 EST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- businessSetup -->
        <test-method signature="businessByIdMockito()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="businessByIdMockito" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- businessByIdMockito -->
        <test-method signature="businessLoginPasswordFailure()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="businessLoginPasswordFailure" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordError">
            <message>
              <![CDATA[Username or Password are incorrect]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordError: Username or Password are incorrect
at com.investing_app.service.BusinessServicesImp.getBusinessLoginService(BusinessServicesImp.java:60)
at dev.businessservicestests.BusinessServicesTests.businessLoginPasswordFailure(BusinessServicesTests.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- businessLoginPasswordFailure -->
        <test-method signature="businessLoginUsernameFailure()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="businessLoginUsernameFailure" finished-at="2022-01-13T00:38:56 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordError">
            <message>
              <![CDATA[Username or Password are incorrect]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordError: Username or Password are incorrect
at com.investing_app.service.BusinessServicesImp.getBusinessLoginService(BusinessServicesImp.java:62)
at dev.businessservicestests.BusinessServicesTests.businessLoginUsernameFailure(BusinessServicesTests.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- businessLoginUsernameFailure -->
        <test-method signature="createBusinessMockito()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="createBusinessMockito" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBusinessMockito -->
        <test-method signature="createBusinessProfileUniqueUsername()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="createBusinessProfileUniqueUsername" finished-at="2022-01-13T00:38:56 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameAlreadyExists">
            <message>
              <![CDATA[That username is already taken! Please try again.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameAlreadyExists: That username is already taken! Please try again.
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:37)
at dev.businessservicestests.BusinessServicesTests.createBusinessProfileUniqueUsername(BusinessServicesTests.java:115)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameAlreadyExists -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBusinessProfileUniqueUsername -->
        <test-method signature="createBusinessNameTooLong()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="createBusinessNameTooLong" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.TooLong">
            <message>
              <![CDATA[Your input is too many characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooLong: Your input is too many characters
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:26)
at dev.businessservicestests.BusinessServicesTests.createBusinessNameTooLong(BusinessServicesTests.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooLong -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBusinessNameTooLong -->
        <test-method signature="createBusinessWithNoName()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="createBusinessWithNoName" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.NoValueException">
            <message>
              <![CDATA[Cannot leave boxes empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NoValueException: Cannot leave boxes empty
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:28)
at dev.businessservicestests.BusinessServicesTests.createBusinessWithNoName(BusinessServicesTests.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NoValueException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createBusinessWithNoName -->
        <test-method signature="createRoleTooLong()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="createRoleTooLong" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.TooLong">
            <message>
              <![CDATA[Your input is too many characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooLong: Your input is too many characters
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:26)
at dev.businessservicestests.BusinessServicesTests.createRoleTooLong(BusinessServicesTests.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooLong -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createRoleTooLong -->
        <test-method signature="loginCredentialsIncorrect()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="loginCredentialsIncorrect" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.UsernameOrPasswordError">
            <message>
              <![CDATA[Username or Password are incorrect]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.UsernameOrPasswordError: Username or Password are incorrect
at com.investing_app.service.BusinessServicesImp.getBusinessLoginService(BusinessServicesImp.java:60)
at dev.businessservicestests.BusinessServicesTests.loginCredentialsIncorrect(BusinessServicesTests.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.UsernameOrPasswordError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginCredentialsIncorrect -->
        <test-method signature="longUserNameCreate()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="longUserNameCreate" finished-at="2022-01-13T00:38:56 EST" duration-ms="1" status="PASS">
          <exception class="com.investing_app.customexceptions.TooLong">
            <message>
              <![CDATA[Your input is too many characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.TooLong: Your input is too many characters
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:26)
at dev.businessservicestests.BusinessServicesTests.longUserNameCreate(BusinessServicesTests.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.TooLong -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- longUserNameCreate -->
        <test-method signature="nonLettersUsedInCreate()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="nonLettersUsedInCreate" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.OnlyLetters">
            <message>
              <![CDATA[Can only use letters in this field]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.OnlyLetters: Can only use letters in this field
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:32)
at dev.businessservicestests.BusinessServicesTests.nonLettersUsedInCreate(BusinessServicesTests.java:107)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.OnlyLetters -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonLettersUsedInCreate -->
        <test-method signature="shortUserNameCreate()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="shortUserNameCreate" finished-at="2022-01-13T00:38:56 EST" duration-ms="0" status="PASS">
          <exception class="com.investing_app.customexceptions.NotEnoughChars">
            <message>
              <![CDATA[Need to fill out the minimum amount of characters]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.investing_app.customexceptions.NotEnoughChars: Need to fill out the minimum amount of characters
at com.investing_app.service.BusinessServicesImp.getCreateBusinessService(BusinessServicesImp.java:30)
at dev.businessservicestests.BusinessServicesTests.shortUserNameCreate(BusinessServicesTests.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.investing_app.customexceptions.NotEnoughChars -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shortUserNameCreate -->
        <test-method signature="viewAllBusinessesMockito()[pri:0, instance:dev.businessservicestests.BusinessServicesTests@691a7f8f]" started-at="2022-01-13T00:38:56 EST" name="viewAllBusinessesMockito" finished-at="2022-01-13T00:38:56 EST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewAllBusinessesMockito -->
      </class> <!-- dev.businessservicestests.BusinessServicesTests -->
      <class name="dev.pitchtests.PitchDAOTests">
        <test-method signature="acceptOffer()[pri:0, instance:dev.pitchtests.PitchDAOTests@17c1bced]" started-at="2022-01-13T00:38:56 EST" name="acceptOffer" finished-at="2022-01-13T00:38:57 EST" duration-ms="516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- acceptOffer -->
        <test-method signature="createPitch()[pri:0, instance:dev.pitchtests.PitchDAOTests@17c1bced]" started-at="2022-01-13T00:38:57 EST" name="createPitch" finished-at="2022-01-13T00:38:57 EST" duration-ms="548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPitch -->
        <test-method signature="makeOffer()[pri:0, instance:dev.pitchtests.PitchDAOTests@17c1bced]" started-at="2022-01-13T00:38:57 EST" name="makeOffer" finished-at="2022-01-13T00:38:58 EST" duration-ms="538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeOffer -->
        <test-method signature="viewPitches()[pri:0, instance:dev.pitchtests.PitchDAOTests@17c1bced]" started-at="2022-01-13T00:38:58 EST" name="viewPitches" finished-at="2022-01-13T00:38:58 EST" duration-ms="546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewPitches -->
      </class> <!-- dev.pitchtests.PitchDAOTests -->
      <class name="dev.businesstests.BusinessDAOTest">
        <test-method signature="getAllBusinesses()[pri:0, instance:dev.businesstests.BusinessDAOTest@1d548a08]" started-at="2022-01-13T00:38:54 EST" name="getAllBusinesses" finished-at="2022-01-13T00:38:54 EST" duration-ms="533" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllBusinesses -->
        <test-method signature="selectBusinessById()[pri:0, instance:dev.businesstests.BusinessDAOTest@1d548a08]" started-at="2022-01-13T00:38:54 EST" name="selectBusinessById" finished-at="2022-01-13T00:38:55 EST" duration-ms="592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectBusinessById -->
        <test-method signature="testCreateBusiness()[pri:0, instance:dev.businesstests.BusinessDAOTest@1d548a08]" started-at="2022-01-13T00:38:55 EST" name="testCreateBusiness" finished-at="2022-01-13T00:38:56 EST" duration-ms="647" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateBusiness -->
        <test-method signature="testGetBusinessByUserName()[pri:0, instance:dev.businesstests.BusinessDAOTest@1d548a08]" started-at="2022-01-13T00:38:56 EST" name="testGetBusinessByUserName" finished-at="2022-01-13T00:38:56 EST" duration-ms="616" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBusinessByUserName -->
      </class> <!-- dev.businesstests.BusinessDAOTest -->
      <class name="dev.commentingtests.CommentingDAOTest">
        <test-method signature="getAllComments()[pri:0, instance:dev.commentingtests.CommentingDAOTest@14ec4505]" started-at="2022-01-13T00:38:58 EST" name="getAllComments" finished-at="2022-01-13T00:38:59 EST" duration-ms="566" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllComments -->
        <test-method signature="selectCommentById()[pri:0, instance:dev.commentingtests.CommentingDAOTest@14ec4505]" started-at="2022-01-13T00:38:59 EST" name="selectCommentById" finished-at="2022-01-13T00:39:00 EST" duration-ms="723" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectCommentById -->
        <test-method signature="testCreateComment()[pri:0, instance:dev.commentingtests.CommentingDAOTest@14ec4505]" started-at="2022-01-13T00:39:00 EST" name="testCreateComment" finished-at="2022-01-13T00:39:00 EST" duration-ms="804" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateComment -->
      </class> <!-- dev.commentingtests.CommentingDAOTest -->
    </test> <!-- JAVA_investing_app -->
  </suite> <!-- Default Suite -->
</testng-results>
